config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'incoming' => 'dashboard#incoming'

  resources :requests

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/request.rb
class Request < ActiveRecord::Base
  # Status and Absense Type Enums
  enum status:       { requested: 'status_requested',
                       approved: 'status_approved',
                       denied: 'status_denied' }

  enum absense_type: { full: 'absense_full',
                       sickness: 'absense_sickness',
                       partial: 'absense_partial' }

  # Non persisted virtual atrributes for partial absense functionality
  attr_accessor :partial_starting, :time_starting, :time_ending

  # Setup relations
  belongs_to :user
  belongs_to :user_assigned, class_name: 'User'

  # Model Validations
  validates :user_id, :user_assigned,
            :absense_type,
            presence: true

  validates :description, length: { minimum: 20 }

  # Validate these attributes only for non partial absense types
  with_options unless: :partial? do |np|
    # Absense starting date should be after tommorow
    np.validates_date :starting, on: :create, on_or_after: :today
    # Absense ending date should be after starting
    np.validates_date :ending, on: :create, after: :starting

    np.validates      :days_off,
                      numericality: { only_integer: true,
                                      greater_than_or_equal_to: 1 }
  end
  # Validate these fields only for partial absense type
  with_options if: :partial?, on: :create do |p|
    p.validates_date :partial_starting, on_or_after: :today
    p.validates_time :time_starting
    p.validates_time :time_ending, after: :time_starting
  end
  # Initialize to Request status
  after_initialize :set_default_values

  # Set default absense_type
  def set_default_values
    self.absense_type ||= Request.absense_types[:full]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests
  has_many :assigned_requests,class_name: "Request",foreign_key: 'user_assigned_id'
  # password encryption and confirmation
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Helper methods for user authentication
  include SessionsHelper
  # Helper methods for user authentication 
  include AuthorizationHelper
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # Confirm user is authenticated
  before_action :logged_in_user
  # Confirm user is authorized as manager to view incoming
  before_action :user_is_manager, only: [:incoming]

  # View own requests
  def index
    @requests = current_user.requests.order(updated_at: :desc)
  end

  # View incoming requests
  def incoming
    @requests = current_user.assigned_requests.order(created_at: :desc)
  end

  def user_is_manager
    redirect_to(root_url) unless current_user.is_manager?
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # Confirm user is authenticated
  before_action :logged_in_user
  # Confirm user is authorized as manager to process requests
  before_action :user_is_assigned_to_request, only: [:show, :update]

  # New Absense Request action
  def new
    @request = Request.new
  end

  def create
    @request = Request.new(create_params)
    # Set request's user to current user
    @request.user = current_user
    # Set request status to Requested
    @request.status = Request.statuses[:requested]

    if @request.partial? && @request.valid?
      begin
        # Combine Date and starting time
        time = Time.parse(@request.time_starting)
        @request.starting = Time.parse(@request.partial_starting)
                                .change(hour: time.hour,
                                        minute: time.min)

        # Combine Date and ending time
        time = Time.parse(@request.time_ending)
        @request.ending = @request.starting
                                  .change(hour: time.hour,
                                          minute: time.min)
      rescue

      end
    end

    if @request.save
      # Send email to assigned manager
      Mailer.notify_incoming_request(@request).deliver_later
      flash[:success] = 'Your absense request has been submitted successfully!'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    # Change request status based on approval or denial
    if params['approve']
      @request.status = Request.statuses[:approved]
    elsif params['deny']
      @request.status = Request.statuses[:denied]
    end

    if @request.update_attributes(update_params)
      # Send email to requester about the status change
      Mailer.notify_changed_request_status(@request).deliver_later
      redirect_to incoming_path
    else
      render 'show'
    end
  end

  private

  # Allowed parameters for request creation
  def create_params
    params.require(:request).permit(:description, :absense_type,
                                    :user_assigned_id, :partial_starting,
                                    :starting, :ending, :days_off,
                                    :time_starting, :time_ending)
  end

  # Allowed parameters for request update
  def update_params
    params.require(:request).permit(:response)
  end

  # Managers should view only their assigned requests
  def user_is_assigned_to_request
    request = Request.find(params[:id])
    redirect_to(root_url) unless request.user_assigned == current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # Show the login form
  def new
    redirect_to :root if logged_in?
  end
  # Authentication from login form
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    # authenticate is provided from gem
    if user && user.authenticate(params[:session][:password])
      log_in user
      if user.is_manager?
        redirect_to :incoming
      else
        redirect_to :root
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  # Signout action
  def destroy
    log_out if logged_in?
    redirect_to login_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/authorization_helper.rb
module AuthorizationHelper
  # Authorization Helper to redirect non authenticated users to login page
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
   session.delete(:user_id)
   @current_user = nil
 end

 
end

app/views/dashboard/incoming.html.erb
<script type="text/javascript">
  $(function () {
    /*  $('.modal-trigger').click(function () {
      var message = $(this).parents('tr').find('.request_response_container').html();
      $('.modal .content').html(message);
      $('.modal').modal('show');
    });
*/
  });
</script>
<div class="ui breadcrumb">
  <a class="section">Dashboard</a>
  <div class="divider">
    /
  </div>
</div>
<div class="ui segment">
  <div class="ui grid">
    <div class="eight wide column">
      <h2>Incoming Requests</h2>
    </div>
  </div>

  <table class="ui red celled unstackable table">
    <thead>
      <tr>
        <th>Employee</th>
        <th>Type</th>
        <th>Starting</th>
        <th>Ending</th>
        <th>Days</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%@requests.each do |request| %>
      <tr class="<%='positive' if request.approved? %>
                 <%='negative' if request.denied? %>">
        <td>
          <strong><%= request.user.name %></strong>
          <p class="detail"><%= request.user.position %></p>
        </td>
        <td>
          <strong><%= t "request_absense_type.#{request.absense_type}" %></strong>
          Absense</td>
        <td>
          <% if request.partial? %>
          <strong><%= l request.starting.to_date, format: :long  %></strong>
          -
          <strong><%= l request.starting, format:  '%H:%M'  %></strong>
        <% else %>
          <strong><%= l request.starting.to_date, format: :long %></strong>
          <% end %>

        </td>
        <td>
          <% if request.partial? %>
          <strong><%= l request.ending, format: '%H:%M'  %></strong>
        <% else %>
          <strong><%= l request.ending.to_date, format: :long %></strong>
          <% end %>
        </td>
        <td class="collapsing center aligned">
          <% unless request.partial? %>
          <a class="ui circular label"><%= request.days_off %>

          </a>
          <% end %>
        </td>

        <td >
          <strong><%= I18n.t "request_status.#{request.status}" %></strong>
        </td>
        <td class="collapsing">
          <div class="request_response_container" style="display:none"><%= request.response %></div>
          <% if request.requested? %>
          <a href="<%= request_path(request) %>" class="ui tiny basic  button modal-trigger">
            <i class="unhide icon"></i>
            View
          </a>
          <% end %>
        </td>
      </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/dashboard/index.html.erb
<script type="text/javascript">
  $(function () {
    $('.modal-trigger').click(function () {
      var closest = $(this).closest('tr').next('tr');
      $("[data-request-response]").not(closest).hide();
      closest.toggle();
    });
    $('.ui .success').delay(4000).fadeOut();
  });
</script>
<div class="ui breadcrumb">
  <a class="section">Dashboard</a>
  <div class="divider">
    /
  </div>
</div>
<% flash.each do |message_type, message| %>
<div class="ui success visible floating message">
  <div class="header">
    Success
  </div>
  <p><%= message %></p>
</div>
<% end %>

<div class="ui modal">
  <div class="header">Response for your absense request</div>
  <div class="content">
    <p></p>
    <p></p>
    <p></p>
  </div>
</div>

<div class="ui segment">
  <div class="ui grid">
    <div class="eight wide column">
      <h2>My Requests</h2>
    </div>
    <div class="eight wide column">
      <a href="/requests/new" class="ui right floated normal primary labeled icon button">
        <i class="icon plane"></i>
        New Absense Request
      </a>
    </div>
  </div>

  <table class="ui red celled unstackable table">
    <thead>
      <tr>
        <th>Type</th>
        <th>Starting</th>
        <th>Ending</th>
        <th>Days</th>
        <th>Assigned To</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%@requests.each do |request| %>
      <tr class="<%='positive' if request.approved? %>
                 <%='negative' if request.denied? %>">
        <td>
          <strong><%= t "request_absense_type.#{request.absense_type}" %></strong>
          Absense</td>
        <td>
          <% if request.partial? %>
          <strong><%= l request.starting.to_date, format: :long  %></strong>
          -
          <strong><%= l request.starting, format:  '%H:%M'  %></strong>
        <% else %>
          <strong><%= l request.starting.to_date, format: :long %></strong>
          <% end %>

        </td>
        <td>
          <% if request.partial? %>
          <strong><%= l request.ending, format: '%H:%M'  %></strong>
        <% else %>
          <strong><%= l request.ending.to_date, format: :long %></strong>
          <% end %>
        </td>
        <td class="collapsing center aligned">
          <% unless request.partial? %>
          <a class="ui circular label"><%=  request.days_off %>

          </a>
          <% end %>
        </td>
        <td><%= request.user_assigned.name %></td>
        <td >
          <strong><%= I18n.t "request_status.#{request.status}" %></strong>
        </td>
        <td class="collapsing">
          <% unless request.requested? %>
          <button class="ui tiny basic button modal-trigger">
            <i class="comment icon"></i>
            Response
          </button>
          <% end %>
        </td>
      </tr>
      <% unless request.requested? %>
      <tr data-request-response style="display:none">
        <td colspan="7">
          <h5><%= request.user_assigned.name %>
            commented:</h5>
          <%= request.response %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/index_manager.html.erb
<script type="text/javascript">
  $(function () {
  /*  $('.modal-trigger').click(function () {
      var message = $(this).parents('tr').find('.request_response_container').html();
      $('.modal .content').html(message);
      $('.modal').modal('show');
    });
*/
  });
</script>
<div class="ui breadcrumb">
  <a class="section">Dashboard</a>
  <div class="divider">
    /
  </div>
</div>
<div class="ui modal">
  <div class="header">Response for your absense request</div>
  <div class="content">
    <p></p>
    <p></p>
    <p></p>
  </div>
</div>

<div class="ui segment">
  <div class="ui grid">
    <div class="eight wide column">
      <h2>Incoming Requests</h2>
    </div>
    <!--
    <div class="eight wide column">
      <a href="/requests/new" class="ui right floated normal primary labeled icon button">
        <i class="icon plane"></i>
        New Absense Request
      </a>
    </div>
  -->
  </div>

  <table class="ui red celled unstackable table">
    <thead>
      <tr>
        <th>Employee</th>
        <th>Type</th>
        <th>Starting</th>
        <th>Ending</th>
        <th>Days</th>
        <th>Status</th>
        <th>Action</th>

      </tr>
    </thead>
    <tbody>
      <%@requests.each do |request| %>
      <tr class="<%='positive' if request.approved? %>
                 <%='negative' if request.denied? %>">

        <td>
          <strong><%= request.user.name %></strong>
          <p class="detail"><%= request.user.position %></p>
        </td>
        <td>
          <strong><%= t "request_absense_type.#{request.absense_type}" %></strong>
          Absense</td>
        <td>
          <% if request.partial? %>
          <strong><%= l request.starting.to_date, format: :long  %></strong>
          -
          <strong><%= l request.starting, format:  '%H:%M'  %></strong>
        <% else %>
          <strong><%= l request.starting.to_date, format: :long %></strong>
          <% end %>

        </td>
        <td>
          <% if request.partial? %>
          <strong><%= l request.ending, format: '%H:%M'  %></strong>
        <% else %>
          <strong><%= l request.ending.to_date, format: :long %></strong>
          <% end %>
        </td>
        <td class="collapsing center aligned">
          <% unless request.partial? %>
          <a class="ui circular label"><%= request.days_off %>

          </a>
          <% end %>
        </td>

        <td >
          <strong><%= I18n.t "request_status.#{request.status}" %></strong>
        </td>
        <td class="collapsing">
          <div class="request_response_container" style="display:none"><%= request.response %></div>
          <% if request.requested? %>
          <a href="<%= request_path(request) %>" class="ui tiny basic  button modal-trigger">
            <i class="unhide icon"></i>
            View
          </a>
          <% end %>
        </td>
      </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ARVSM | Absence Request and Vacation Schedule Management</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/components/icon.min.css'>
    <style type="text/css">
      body {
        background-color: #DADADA;
      }

    </style>

  </head>
  <body>
    <div class="ui container">
      <% if logged_in? %>
      <div id="menus" class="ui  inverted black menu">
        <div class="header item">
          AVRSM
        </div>
          <%= link_to "My Requests", root_path,
                      class:'ui red item' %>

          <%= link_to "Incoming Requets", incoming_path,
                      class:'ui red item' if current_user.is_manager? %>



        <div class="right menu">
          <div class="vertically fitted red item">
      <%=current_user.name %>
    </div>
         <%= link_to "Log out", logout_path, method: :delete,class:'ui item' %>
        </div>
      </div>
    <% else %>

      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/requests/new.html.erb
<script type="text/javascript">
  $(function () {
    $('.ui.radio.checkbox').checkbox();
    $('.ui.dropdown').dropdown();

    jQuery('#request_starting').datetimepicker({timepicker: false, format: 'Y/m/d'});
    jQuery('#request_ending').datetimepicker({timepicker: false, format: 'Y/m/d'});
    jQuery('#request_partial_starting').datetimepicker({timepicker: false, format: 'Y/m/d'});

    jQuery('#request_time_starting').datetimepicker({timepicker: true, datepicker: false, format: 'H:i'});
    jQuery('#request_time_ending').datetimepicker({timepicker: true, datepicker: false, format: 'H:i'});
    var AbsenseType = $('input:radio');

    AbsenseType.change(function () {
      if ($(this).val() == 'partial') {
        $("#absense_fields").hide();
        $("#absense_partial_fields").show();
      } else {
        $("#absense_fields").show();
        $("#absense_partial_fields").hide();
      }
    });

    AbsenseType.filter(':checked').change();
  });
</script>


<div class="ui breadcrumb">
  <a class="section" href="/">Dashboard</a>
  <div class="divider">
    /
  </div>
   <div class="active section">New Absense Request</div>
</div>

<div class="ui segment">
  <div class="ui form <%= @request.errors.any? ? 'error' : '' %>">
    <h3 class="ui dividing header">Create a New Absense Request</h3>

    <div class="ui error message">
      <div class="header">Please fix the following errors</div>
      <ul class="list">
        <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<%= form_for(@request) do |f| %>
    <div class="inline fields">
      <label>Select your absense type</label>
      <div class="field">
        <div class="ui radio checkbox">
          <%= f.radio_button :absense_type, 'full'  %>
          <label>Full</label>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <%= f.radio_button :absense_type, 'sickness'  %>
          <label>Sickness</label>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <%= f.radio_button :absense_type, 'partial'  %>
          <label>Partial</label>
        </div>
      </div>
    </div>

    <div id="absense_fields" class="fields">
      <div class="field">
        <label>Absense Start Date</label>
        <%= f.text_field :starting %>
      </div>
      <div class="field">
        <label>Absense End Date</label>
        <%= f.text_field :ending %>
      </div>
      <div class="field">
        <label>Working Days</label>
        <%= f.text_field :days_off %>
      </div>
    </div>

    <div id="absense_partial_fields" class="fields">
      <div class="field">
        <label>Absense Date</label>
        <%= f.text_field :partial_starting , value: @request.partial_starting %>
      </div>
      <div class="field">
        <label>Hour Start</label>
        <%= f.text_field :time_starting , value: @request.time_starting %>
      </div>
      <div class="field">
        <label>Hour End</label>
        <%= f.text_field :time_ending , value: @request.time_ending %>
      </div>
    </div>

    <div class="field">
      <label>Assign to</label>
      <%= f.select(:user_assigned_id,
                   User.where(is_manager:true)
                       .where.not(id:current_user.id)
                       .collect {|p| [ p.name, p.id ] },
                   {},{ class: "ui search dropdown"} )%>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, rows:5 %>
    </div>
    <%= f.submit "Submit Request", class: "ui green button" %>
    <% end %>
  </div>
</div>

app/views/requests/show.html.erb
<script type="text/javascript">
  $(function () {
    $('.ui.radio.checkbox').checkbox();
    $('.ui.dropdown').dropdown();
  });
</script>

<div class="ui breadcrumb">
  <a class="section" href="/">Dashboard</a>
  <div class="divider">
    /
  </div>
  <div class="active section">Validate Request</div>
</div>

<div class="ui segments">
  <div class="ui segment">

    <h4 class="ui image header">
      <img src="/chris.png" class="ui mini rounded image">
      <div class="content">
        <%= @request.user.name %>
        <div class="sub header">
          <%= @request.user.position %>
        </div>
      </div>
    </h4>
  </div>
  <div class="ui segment">

    <div class="ui form">

      <div class="fields">
        <div class="field">
          <label>Absense Type</label>
          <a class="ui label"><%= t "request_absense_type.#{@request.absense_type}" %>
            Absense
          </a>
        </div>
      </div>

      <div class="fields">
        <% if @request.partial? %>

        <div class="field">
          <label>Date</label>
          <%= l @request.starting.to_date, format: :long  %>
        </div>
        <div class="field">
          <label>Starting</label>
          <%= l @request.starting, format:  '%H:%M'  %>
        </div>
        <div class="field">
          <label>Ending</label>
          <%= l @request.ending, format:  '%H:%M'  %>
        </div>

      <% else %>

        <div class="field">
          <label>Starting</label>
          <%= l @request.starting.to_date, format: :long  %>
        </div>
        <div class="field">
          <label>Ending</label>
          <%= l @request.ending.to_date, format: :long  %>
        </div>
        <div class="field">
          <label>Working Days</label>
          <a class="ui tiny label"><%= @request.days_off %></a>
        </div>

        <% end %>

      </div>

      <div class="fields">
        <div class="field">
          <label>Description</label>
          <div><%= @request.description %></div>
        </div>
      </div>

    </div>

  </div>

  <div class="ui segment">
    <%= form_for(@request) do |f| %>
    <div class="ui form">

      <div class="ui error message">
        <div class="header">Please fix the following errors</div>
        <ul class="list">
          <% @request.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>

      <div class="field">
        <label>Reply comment</label>
        <%= f.text_area :response, rows:5 %>
      </div>
      <div class=" content">
        <div class="ui  buttons">
          <%= f.submit 'Approve' , class: 'ui positive  submit button', name: 'approve' %>
          <div class="or"></div>
          <%= f.submit 'Deny' , class: 'ui negative  submit button',name:'deny' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>
</div>